parameters:
  name: 'Build_Job'
  poolName: ''
  builConfig: ''
  artifactName: 'JustFunctional'
jobs:
  - job: ${{ parameters.name }}
    pool:
      name: ${{parameters.poolName}}        
    steps:
    - task: gitversion/setup@0
      displayName: Install Git Version
      inputs:
        versionSpec: '5.x'

    - task: gitversion/execute@0
      displayName: Determine Version
      inputs:
        useConfigFile: true
        configFilePath: 'SolutionItems\Pipelines\JustFunctional.Core\gitversion.yml'

    - task: CmdLine@2
      displayName: Print Nuget versions
      inputs:
        script: | 
            echo NuGetVersion: $(GitVersion.NuGetVersion)
            echo NuGetVersionV2: $(GitVersion.NuGetVersionV2)
            echo NuGetPreReleaseTagV2: $(GitVersion.NuGetPreReleaseTagV2)
            echo NuGetPreReleaseTag: $(GitVersion.NuGetPreReleaseTag)  

    - task: DotNetCoreCLI@2
      displayName: '.Net Core Restore - ${{parameters.builConfig}}'
      inputs:
        command: 'restore'
        arguments: '--configuration ${{parameters.builConfig}}'
        projects: 'JustFunctional.sln'
    
    - task: DotNetCoreCLI@2
      displayName: '.Net Core Build - ${{parameters.builConfig}}'
      inputs:
        command: 'build'
        arguments: '--configuration ${{parameters.builConfig}}'
        projects: 'JustFunctional.sln'

    - task: DotNetCoreCLI@2
      displayName: '.Net Core Run Tests - ${{parameters.builConfig}}'
      inputs:
        command: test
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration ${{parameters.builConfig}}'

    - task: DotNetCoreCLI@2
      displayName: 'Net Core Nuget Pack - ${{parameters.builConfig}}' 
      inputs: 
        command: 'custom'
        custom: 'pack'
        arguments: "
         --configuration ${{parameters.builConfig}} 
         --no-restore 
         --no-build 
         --output $(Build.ArtifactStagingDirectory)/${{parameters.builConfig}} 
         -p:PackageVersion=$(GitVersion.NuGetVersion)"
        
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact  - ${{parameters.builConfig}}'
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: '${{parameters.artifactName}}'