parameters:
  name: 'Build_Job'
  poolName: ''
  builConfig: ''
  artifactName: ''
jobs:
  - job: ${{ parameters.name }}
    pool:
      name: ${{parameters.poolName}}        
    steps:
    - task: gitversion/setup@0
      displayName: Install Git Version
      inputs:
        versionSpec: '5.x'

    - task: gitversion/execute@0
      displayName: Determine Version
      inputs:
        useConfigFile: true
        configFilePath: 'SolutionItems\Pipelines\JustFunctional.Core\gitversion.yml'

    - task: CmdLine@2
      displayName: Print Nuget versions
      inputs:
        script: | 
            echo NuGetVersion: $(GitVersion.NuGetVersion)
            echo NuGetVersionV2: $(GitVersion.NuGetVersionV2)
            echo NuGetPreReleaseTagV2: $(GitVersion.NuGetPreReleaseTagV2)
            echo NuGetPreReleaseTag: $(GitVersion.NuGetPreReleaseTag)  

    - task: DotNetCoreCLI@2
      displayName: '.Net Core Restore - ${{parameters.builConfig}}'
      inputs:
        command: 'restore'
        arguments: '--configuration ${{parameters.builConfig}}'
        projects: 'JustFunctional.sln'
    
    - task: DotNetCoreCLI@2
      displayName: '.Net Core Build - ${{parameters.builConfig}}'
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration ${{parameters.builConfig}}'
        projects: 'JustFunctional.sln'
    
    - task: DotNetCoreCLI@2
      displayName: '.Net Core - Install tools from local manifest'
      inputs:
        command: custom
        custom: tool
        arguments: 'restore'

    - task: DotNetCoreCLI@2
      displayName: '.Net Core Run Tests - ${{parameters.builConfig}}'
      inputs:
        command: 'test'
        arguments: '--no-build --configuration $(buildConfiguration) 
            /p:CollectCoverage=true 
            /p:CoverletOutputFormat=cobertura 
            /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'
        publishTestResults: true
        projects: '**/*Tests/*.csproj'
    
    - task: DotNetCoreCLI@2
      displayName: '.Net Core Tests - Create Code Coverage Report'
      inputs:
        command: custom
        custom: tool
        arguments: 'run reportgenerator 
                    -reports:$(Build.SourcesDirectory)/**/coverage.cobertura.xml 
                    -targetdir:$(Build.SourcesDirectory)/CodeCoverage 
                    -reporttypes:HtmlInline_AzurePipelines'
    
    - task: PublishCodeCoverageResults@1
      displayName: '.Net Core Tests - Publish Code Coverage Report'
      inputs:
        codeCoverageTool: 'cobertura'
        summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'

    - task: DotNetCoreCLI@2
      displayName: 'Net Core Nuget Pack - ${{parameters.builConfig}}' 
      inputs: 
        command: 'custom'
        custom: 'pack'
        arguments: "
                    --configuration ${{parameters.builConfig}} 
                    --no-restore 
                    --no-build 
                    --output $(Build.ArtifactStagingDirectory)/${{parameters.builConfig}} 
                    -p:PackageVersion=$(GitVersion.NuGetVersion)"
    
    - publish: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Publish Artifact  - ${{parameters.artifactName}}'
      artifact: ${{parameters.artifactName}}