parameters:
  name: 'Release Job'
  poolName: ''
  builConfig: ''
  artifactName: ''
  nugetApiKey: ''

jobs:
  - deployment: 'release'
    variables:
        nugetUrl: 'https://api.nuget.org/v3/index.json'
    displayName: '${{parameters.name}}'
    environment: 'production'
    pool:
      name: ${{parameters.poolName}} 
    strategy:
        runOnce: 
            deploy:
                steps:
                - task: DownloadPipelineArtifact@2
                  displayName: 'Download Artifact  - ${{parameters.artifactName}}'
                  inputs:
                    source: current
                    path: $(System.ArtifactsDirectory)/${{parameters.artifactName}}
                    artifact:  ${{parameters.artifactName}}
                    
                - task: DotNetCoreCLI@2
                  displayName: 'NuGet push'
                  inputs:
                    command: custom
                    custom: nuget
                    arguments: >
                      push $(System.ArtifactsDirectory)\${{parameters.artifactName}}\${{parameters.builConfig}}\*.nupkg
                      -s $(nugetUrl)
                      -k ${{parameters.nugetApiKey}} 
                      --skip-duplicate              